spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

fixer:
  url: http://data.fixer.io/api/
  access-key: f197f839533b0723b36e4c577426b187

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO